#include <gtk/gtk.h>
#include <stdio.h>
#include "inventory.h"
#include "gui.h"
#include "utils.h"

static void on_window_destroy(GtkWidget *widget, gpointer data) {
    (void)widget;
    (void)data;
    gtk_main_quit();
}

static void setup_enhanced_css() {
    GtkCssProvider *provider = gtk_css_provider_new();
    
    const char *enhanced_css = 
        "/* Enhanced Base styling with better typography */"
        "window {"
        "    background-color: #fafbfc;"
        "    color: #1a202c;"
        "    font-family: 'Segoe UI', 'Roboto', 'Ubuntu', sans-serif;"
        "    font-size: 15px;"
        "}"
        ""
        "/* Smaller window control buttons */"
        "headerbar button {"
        "    min-width: 28px;"
        "    min-height: 28px;"
        "    padding: 4px;"
        "}"
        ""
        "/* Enhanced Header with gradient and proper contrast */"
        ".app-header {"
        "    background: linear-gradient(135deg, #1e3a8a, #3b82f6, #60a5fa);"
        "    color: white;"
        "    padding: 20px 24px;"
        "    border-radius: 12px 12px 0 0;"
        "    box-shadow: 0 4px 16px rgba(59, 130, 246, 0.2);"
        "}"
        ""
        "/* App title - Extra large and bold */"
        ".app-title {"
        "    font-size: 30px;"
        "    font-weight: 800;"
        "    color: white;"
        "    text-shadow: 0 2px 4px rgba(0, 0, 0, 0.3);"
        "    margin: 4px 0;"
        "    letter-spacing: 0.5px;"
        "}"
        ""
        "/* App subtitle - Medium size */"
        ".app-subtitle {"
        "    font-size: 17px;"
        "    font-weight: 500;"
        "    color: rgba(255, 255, 255, 0.95);"
        "    margin-top: 6px;"
        "    letter-spacing: 0.3px;"
        "}"
        ""
        "/* Section titles - Large and prominent */"
        ".section-title {"
        "    font-size: 19px;"
        "    font-weight: 700;"
        "    color: #2d3748;"
        "    margin: 12px 0 8px 0;"
        "    text-transform: uppercase;"
        "    letter-spacing: 0.8px;"
        "}"
        ""
        "/* Form labels - Medium weight and dark */"
        ".form-label {"
        "    font-size: 16px;"
        "    font-weight: 600;"
        "    color: #2d3748;"
        "    margin-right: 12px;"
        "    text-align: right;"
        "}"
        ""
        "/* Toolbar text */"
        ".toolbar-text {"
        "    font-size: 14px;"
        "    font-weight: 500;"
        "    color: #4a5568;"
        "    letter-spacing: 0.2px;"
        "}"
        ""
        "/* FIXED: Normal input fields with 14px BLACK typed text */"
        "entry,"
        "searchentry,"
        ".form-input,"
        ".search-entry {"
        "    background-color: #ffffff;"
        "    border: 2px solid #e2e8f0;"
        "    border-radius: 8px;"
        "    padding: 12px 16px;"
        "    font-size: 14px;"
        "    color: #000000;"
        "    min-height: 20px;"
        "    transition: all 0.2s ease;"
        "}"
        ""
        "/* CRITICAL: Multiple approaches to force BLACK 14px text in GTK entries */"
        "entry {"
        "    color: #000000 !important;"
        "    font-size: 14px !important;"
        "    -gtk-icon-effect: none;"
        "}"
        ""
        "entry text {"
        "    color: #000000 !important;"
        "    font-size: 14px !important;"
        "    font-weight: 600 !important;"
        "    background-color: transparent !important;"
        "}"
        ""
        "entry > text {"
        "    color: #000000 !important;"
        "    font-size: 14px !important;"
        "    font-weight: 600 !important;"
        "}"
        ""
        "searchentry {"
        "    color: #000000 !important;"
        "    font-size: 14px !important;"
        "}"
        ""
        "searchentry text {"
        "    color: #000000 !important;"
        "    font-size: 14px !important;"
        "    font-weight: 600 !important;"
        "    background-color: transparent !important;"
        "}"
        ""
        "searchentry > text {"
        "    color: #000000 !important;"
        "    font-size: 14px !important;"
        "    font-weight: 600 !important;"
        "}"
        ""
        "/* Target any text widget that might be inside entries */"
        "text {"
        "    color: #000000 !important;"
        "    font-size: 14px !important;"
        "}"
        ""
        "/* Caret color for visibility */"
        "entry, searchentry {"
        "    caret-color: #000000 !important;"
        "}"
        ""
        "/* Focus states with black text preserved */"
        "entry:focus,"
        "searchentry:focus {"
        "    border-color: #3b82f6;"
        "    box-shadow: 0 0 0 3px rgba(59, 130, 246, 0.15);"
        "    outline: none;"
        "    background-color: #ffffff;"
        "    color: #000000 !important;"
        "}"
        ""
        "entry:focus text,"
        "searchentry:focus text {"
        "    color: #000000 !important;"
        "    font-size: 14px !important;"
        "}"
        ""
        "/* Selection colors to ensure visibility */"
        "entry:focus:selected,"
        "searchentry:focus:selected,"
        "entry text:selected,"
        "searchentry text:selected {"
        "    background-color: #3b82f6 !important;"
        "    color: #ffffff !important;"
        "}"
        ""
        "/* Placeholder text styling */"
        "entry placeholder,"
        "searchentry placeholder {"
        "    color: #9ca3af !important;"
        "    font-style: italic;"
        "    font-weight: 400 !important;"
        "    font-size: 14px !important;"
        "}"
        ""
        "/* FIXED: Green Add button with WORKING hover */"
        "button.primary-button {"
        "    background: linear-gradient(135deg, #10b981, #059669);"
        "    color: white;"
        "    border: none;"
        "    border-radius: 8px;"
        "    padding: 10px 20px;"
        "    font-size: 15px;"
        "    font-weight: 600;"
        "    min-height: 38px;"
        "    transition: all 0.2s ease;"
        "    text-shadow: none;"
        "}"
        ""
        "button.primary-button:hover {"
        "    background: linear-gradient(135deg, #059669, #047857) !important;"
        "    transform: translateY(-1px);"
        "    box-shadow: 0 6px 20px rgba(16, 185, 129, 0.4);"
        "}"
        ""
        "/* FIXED: Gray Secondary button with WORKING hover */"
        "button.secondary-button {"
        "    background: linear-gradient(135deg, #6b7280, #4b5563);"
        "    color: white;"
        "    border: none;"
        "    border-radius: 8px;"
        "    padding: 10px 20px;"
        "    font-size: 15px;"
        "    font-weight: 600;"
        "    min-height: 38px;"
        "    transition: all 0.2s ease;"
        "}"
        ""
        "button.secondary-button:hover {"
        "    background: linear-gradient(135deg, #4b5563, #374151) !important;"
        "    transform: translateY(-1px);"
        "    box-shadow: 0 6px 20px rgba(107, 114, 128, 0.4);"
        "}"
        ""
        "/* Red Danger button with working hover */"
        "button.danger-button {"
        "    background: linear-gradient(135deg, #ef4444, #dc2626);"
        "    color: white;"
        "    border: none;"
        "    border-radius: 8px;"
        "    padding: 10px 20px;"
        "    font-size: 15px;"
        "    font-weight: 600;"
        "    min-height: 38px;"
        "    transition: all 0.2s ease;"
        "}"
        ""
        "button.danger-button:hover {"
        "    background: linear-gradient(135deg, #dc2626, #b91c1c) !important;"
        "    transform: translateY(-1px);"
        "    box-shadow: 0 6px 20px rgba(239, 68, 68, 0.4);"
        "}"
        ""
        "/* Default button styling (fallback) */"
        "button {"
        "    background: linear-gradient(135deg, #3b82f6, #1d4ed8);"
        "    color: white;"
        "    border: none;"
        "    border-radius: 8px;"
        "    padding: 10px 20px;"
        "    font-size: 15px;"
        "    font-weight: 600;"
        "    min-height: 38px;"
        "    transition: all 0.2s ease;"
        "    text-shadow: none;"
        "}"
        ""
        "button:hover {"
        "    background: linear-gradient(135deg, #2563eb, #1e40af) !important;"
        "    transform: translateY(-1px);"
        "    box-shadow: 0 6px 20px rgba(59, 130, 246, 0.4);"
        "}"
        ""
        "/* Enhanced toolbar */"
        ".main-toolbar {"
        "    background: linear-gradient(to bottom, #f8fafc, #f1f5f9);"
        "    border-bottom: 2px solid #e2e8f0;"
        "    padding: 12px 16px;"
        "    min-height: 50px;"
        "}"
        ""
        "/* Toolbar buttons */"
        "button.toolbar-button {"
        "    background: linear-gradient(to bottom, #ffffff, #f7fafc);"
        "    color: #4a5568;"
        "    border: 1px solid #cbd5e0;"
        "    border-radius: 6px;"
        "    font-weight: 500;"
        "    font-size: 14px;"
        "    padding: 8px 16px;"
        "    min-height: 34px;"
        "    transition: all 0.2s ease;"
        "}"
        ""
        "button.toolbar-button:hover {"
        "    background: linear-gradient(to bottom, #f7fafc, #edf2f7) !important;"
        "    color: #2d3748;"
        "    border-color: #a0aec0;"
        "    transform: none;"
        "    box-shadow: none;"
        "}"
        ""
        "/* Enhanced TreeView with better contrast */"
        ".data-table, treeview {"
        "    background-color: #ffffff;"
        "    color: #1a202c;"
        "    border: 2px solid #e2e8f0;"
        "    border-radius: 8px;"
        "    font-size: 15px;"
        "    font-weight: 500;"
        "}"
        ""
        "treeview:selected {"
        "    background-color: #3b82f6;"
        "    color: white;"
        "    font-weight: 600;"
        "}"
        ""
        "/* FIXED: Larger table headers with increased font size */"
        "treeview header button {"
        "    background: linear-gradient(to bottom, #f7fafc, #edf2f7);"
        "    color: #2d3748;"
        "    border: 1px solid #cbd5e0;"
        "    font-weight: 700;"
        "    font-size: 18px !important;"
        "    text-transform: uppercase;"
        "    letter-spacing: 0.8px;"
        "    padding: 14px 12px;"
        "    min-height: 44px;"
        "}"
        ""
        "treeview header button:hover {"
        "    background: linear-gradient(to bottom, #edf2f7, #e2e8f0);"
        "    color: #1a202c;"
        "}"
        ""
        "/* Enhanced input frame */"
        ".input-frame {"
        "    background-color: #f8fafc;"
        "    border: 2px solid #e2e8f0;"
        "    border-radius: 12px;"
        "    padding: 8px;"
        "    box-shadow: 0 2px 8px rgba(0, 0, 0, 0.05);"
        "}"
        ""
        ".input-frame > label {"
        "    font-weight: 700;"
        "    font-size: 18px;"
        "    color: #2d3748;"
        "    letter-spacing: 0.3px;"
        "}"
        ""
        "/* Enhanced status bar */"
        ".status-bar {"
        "    background: linear-gradient(135deg, #2d3748, #4a5568);"
        "    color: white;"
        "    padding: 14px 20px;"
        "    font-size: 15px;"
        "    font-weight: 600;"
        "    border-radius: 0 0 12px 12px;"
        "    text-shadow: 0 1px 2px rgba(0, 0, 0, 0.2);"
        "}"
        ""
        "/* Enhanced main content area */"
        ".main-content {"
        "    background-color: #ffffff;"
        "    border-radius: 0 0 12px 12px;"
        "    box-shadow: 0 4px 16px rgba(0, 0, 0, 0.1);"
        "}"
        ""
        "/* Enhanced inventory table container */"
        ".inventory-table {"
        "    background-color: #ffffff;"
        "    border: 2px solid #e2e8f0;"
        "    border-radius: 10px;"
        "    box-shadow: 0 2px 8px rgba(0, 0, 0, 0.06);"
        "}"
        ""
        "/* Dialog styling */"
        "dialog {"
        "    background-color: white;"
        "    color: #1a202c;"
        "    border-radius: 12px;"
        "    box-shadow: 0 12px 32px rgba(0, 0, 0, 0.15);"
        "}"
        ""
        "messagedialog {"
        "    background-color: white;"
        "}"
        ""
        "messagedialog label {"
        "    color: #1a202c;"
        "    font-size: 16px;"
        "    font-weight: 500;"
        "}"
        ""
        "/* Scrolled window styling */"
        "scrolledwindow {"
        "    background-color: white;"
        "    border: 2px solid #e2e8f0;"
        "    border-radius: 8px;"
        "}";
    
    gtk_css_provider_load_from_data(provider, enhanced_css, -1, NULL);
    gtk_style_context_add_provider_for_screen(
        gdk_screen_get_default(),
        GTK_STYLE_PROVIDER(provider),
        GTK_STYLE_PROVIDER_PRIORITY_APPLICATION
    );
    g_object_unref(provider);
}

int main(int argc, char *argv[]) {
    gtk_init(&argc, &argv);
    
    AppData app_data = {0};
    Inventory inventory;
    inventory_init(&inventory);
    app_data.inventory = &inventory;
    app_data.selected_id = -1;
    
    // Apply enhanced CSS styling
    setup_enhanced_css();
    
    // Create main window
    app_data.window = create_main_window(&app_data);
    g_signal_connect(app_data.window, "destroy", G_CALLBACK(on_window_destroy), NULL);
    
    // Try to load existing inventory
    if (load_inventory_from_file(&inventory, "inventory.csv")) {
        refresh_tree_view(&app_data);
        update_status(&app_data, "📂 Inventory loaded successfully! Ready to manage your stock.");
    } else {
        update_status(&app_data, "🚀 StockFlow Ready - Welcome to your professional inventory system!");
    }
    
    // Show the application
    gtk_widget_show_all(app_data.window);
    gtk_main();
    
    return 0;
}